<a href="https://colab.research.google.com/github/ppunkz/CE888_DS/blob/master/Lab%205%20/%20Recommender%20System.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np

#  Load the data from ``jester-data-1.csv''


In [17]:
df = pd.read_csv('https://raw.githubusercontent.com/albanda/CE888/master/lab5-recommender/jester-data-1.csv', header=None)
df

0      1      2      3      4    ...    96     97     98     99     100
0       74  -7.82   8.79  -9.66  -8.16  ...  99.00  -5.63  99.00  99.00  99.00
1      100   4.08  -0.29   6.36   4.37  ...  -2.14   3.06   0.34  -4.32   1.07
2       49  99.00  99.00  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
3       48  99.00   8.35  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
4       91   8.50   4.61  -4.17  -5.39  ...   1.55   3.11   6.55   1.80   1.60
...    ...    ...    ...    ...    ...  ...    ...    ...    ...    ...    ...
24978  100   0.44   7.43   9.08   2.33  ...   9.03   6.55   8.69   8.79   7.43
24979   91   9.13  -8.16   8.59   9.08  ...  -8.20  -7.23  -8.59   9.13   8.45
24980   39  99.00  99.00  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
24981   37  99.00  99.00  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
24982   72   2.43   2.67  -3.98   4.27  ...  99.00  99.00  99.00  99.00  99.00

[24983 rows x 101 columns]

In [18]:
arr = df.values
print(arr.shape)

(24983, 101)


In [19]:
rated = np.where(arr!=99)
rated

(array([    0,     0,     0, ..., 24982, 24982, 24982]),
 array([ 0,  1,  2, ..., 70, 71, 87]))

In [20]:
rated = np.where(arr!=99)
print(len(rated[0]), rated[1].shape)

1835357 (1835357,)


# Using the helper function provided in the helper_function notebook (or create your own), label 10% of the dataset cells as 99. This is your validation set. Keep the the actual values of the cells so you can use them later.

In [0]:
def replace(orig, percentage=0.1):
  """
  Replaces 'percentage'% of the original values in 'orig' with 99's
  :param orig: original data array
  :param percentage: percentage of values to replace (0<percentage<1)
  """
  new_data = orig.copy()
  rated = np.where(arr!=99)
  n_rated = len(rated[0])
  idx = np.random.choice(n_rated, size=int(percentage*n_rated), replace=False)
  new_data[rated[0][idx], rated[1][idx]] = 99
  return new_data, (rated[0][idx], rated[1][idx])

In [0]:
new_arr, idx = replace(arr, 0.1)

In [23]:
arr[idx[0][0], idx[1][0]]

5.68

In [24]:
new_arr[idx[0][0], idx[1][0]]

99.0

In [0]:
n_latent_factors = 2

user_ratings = df.values
# Initialise as random values
latent_user_preferences = np.random.random((user_ratings.shape[0], n_latent_factors))
latent_item_features = np.random.random((user_ratings.shape[1], n_latent_factors))

In [0]:
def predict_rating(user_id, item_id):
    """ Predict a rating given a user_id and an item_id.
    """
    user_preference = latent_user_preferences[user_id]
    item_preference = latent_item_features[item_id]
    return user_preference.dot(item_preference)


def train(user_id, item_id, rating, alpha=0.0001):
    
    #print item_id
    prediction_rating = predict_rating(user_id, item_id)
    err =  prediction_rating - rating
    #print err
    user_pref_values = latent_user_preferences[user_id][:]
    latent_user_preferences[user_id] -= alpha * err * latent_item_features[item_id]
    latent_item_features[item_id] -= alpha * err * user_pref_values
    return err
    

def sgd(iterations=300000):
    """ Iterate over all users and all items and train for 
        a certain number of iterations
    """
    for iteration in range(iterations):
        error = []
        for user_id in range(latent_user_preferences.shape[0]):
            for item_id in range(latent_item_features.shape[0]):
                rating = user_ratings[user_id][item_id]
                if rating != 99:
                    err = train(user_id, item_id, rating)
                    error.append(err)
        mse = (np.array(error) ** 2).mean()   
        if (iteration % 1) == 0:
            print(mse)


In [0]:
sgd(15)

24.554625455698442
24.500366192158708


In [31]:
predictions = latent_user_preferences.dot(latent_item_features.T)
predictions

array([[ 7.45842842e+01,  7.63114891e-01,  5.97104636e-01, ...,
         9.32557860e-01,  5.96119801e-02,  1.52282272e+00],
       [ 9.65821782e+01,  1.15879806e+00,  6.59829257e-02, ...,
         8.15115612e-01,  3.15628808e-02,  1.11415823e+00],
       [ 5.47247782e+01,  6.80590962e-01, -6.21014579e-02, ...,
         4.06642811e-01,  1.14649088e-02,  5.10627263e-01],
       ...,
       [ 3.79392074e+01,  3.74588584e-01,  3.60064716e-01, ...,
         5.05631982e-01,  3.39577481e-02,  8.42948414e-01],
       [ 3.77835773e+01,  5.10860562e-01, -2.12671889e-01, ...,
         1.86527112e-01, -3.03959426e-03,  1.46606180e-01],
       [ 7.43134215e+01,  7.57553005e-01,  6.06503799e-01, ...,
         9.35590813e-01,  6.01418422e-02,  1.53132284e+00]])

In [0]:
values = [zip(user_ratings[i], predictions[i]) for i in range(predictions.shape[0])]
comparison_data = pd.DataFrame(values)
comparison_data.columns = df.columns

In [33]:
comparison_data
# For each data point, the number on the left is the original value from the dataset, the number on the right is the prediction

0    ...                         100
0        (74.0, 74.58428421284829)  ...  (99.0, 1.5228227234226708)
1       (100.0, 96.58217823618847)  ...   (1.07, 1.114158227988985)
2         (49.0, 54.7247782371331)  ...  (99.0, 0.5106272633733924)
3       (48.0, 49.887463125614055)  ...  (99.0, 0.9344292102289038)
4        (91.0, 93.77630279527729)  ...   (1.6, 1.5154291777586832)
...                            ...  ...                         ...
24978  (100.0, 102.99756109049818)  ...  (7.43, 1.7709535249843784)
24979    (91.0, 85.47945755037847)  ...  (8.45, 1.0660683227510728)
24980    (39.0, 37.93920742371911)  ...   (99.0, 0.842948414135081)
24981    (37.0, 37.78357734140102)  ...  (99.0, 0.1466061798908258)
24982    (72.0, 74.31342145020615)  ...    (99.0, 1.53132283930479)

[24983 rows x 101 columns]