<a href="https://colab.research.google.com/github/ppunkz/CE888_DS/blob/master/Lab1/Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Questions to be done during the lab:

### 1.Create a (4 x 2) integer array and print it's attributes


In [3]:
import numpy as np
a = np.array([[1,2],[3,4],[5,6],[7,8]])
print(a)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


### 2.Create an array of dimension (1,10) and sort it in ascending and descending order


In [37]:
b = np.random.randint(1,10,10)
b = np.sort(b)
c = np.sort(b)[::-1]
print('ascending number')
print(b)
print('descending number')
print(c)

ascending number
[1 3 4 4 6 6 7 7 7 8]
descending number
[8 7 7 7 6 6 4 4 3 1]


### 3. Convert an 1D array [1 2 3 4 5 6 7 8 9] to 2D array [[1 2 3], [4 5 6], [7 8 9]]

In [43]:
d = np.arange(1,10).reshape((3,3))

print('2D array:','\n',d)


2D array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


### 4.Stack two arrays of any size horizontally and vertically

In [105]:
x = np.random.randint(1,10,5)
y = np.random.randint(1,10,5)
xy = np.stack((x,y), axis =0)
print('horizontal stack','\n', xy)
xy1 = np.stack((x,y), axis=1)
print('vertical stack','\n', xy1)

horizontal stack 
 [[8 9 1 8 7]
 [2 3 6 7 5]]
vertical stack 
 [[8 2]
 [9 3]
 [1 6]
 [8 7]
 [7 5]]


### 5. Create two array of same size and find commom elements

In [68]:
def common_member(x, y):
  x_set = set(x)
  y_set = set(y)
  if len(x_set.intersection(y_set)) > 0:
      return(x_set.intersection(y_set))
  else:
      return("no common elements")

x = np.arange(1,10)
y = np.arange(5,16)
print('common elements of x and y variables:','\n',common_member(x, y))

common elements of x and y variables: 
 {5, 6, 7, 8, 9}


### 6. Create a 2D array of 5 by 5 and find the min and max values from each row and each column

In [78]:
ff = np.random.randint(1,25,25).reshape((5,5))
print('array of 5 by 5:', '\n',ff)
max_row = np.amax(ff, axis=0)
min_row = np.amin(ff, axis=0)
print('max values from each row:','\n',max_row)
print('min values from each row:','\n',min_row)
max_col = np.amax(ff, axis=1)
min_col = np.amin(ff, axis=1)
print('max values from each row:','\n',max_col)
print('min values from each row:','\n',min_col)

array of 5 by 5: 
 [[21  5 18  8 23]
 [14 15  5 22 19]
 [ 1  9  6 16 12]
 [10  2  2  6 19]
 [15  6 16  1 21]]
max values from each row: 
 [21 15 18 22 23]
min values from each row: 
 [ 1  2  2  1 12]
max values from each row: 
 [23 22 16 19 21]
min values from each row: 
 [5 5 1 2 1]


### 7. Create an array of size 100 and compute the mean, median, standard deviation.

In [86]:
x = np.random.randint(1,1000,100)
print(' mean','\n',np.mean(x),'\n',
      'median','\n',np.median(x),'\n',
      'standard deviation','\n',np.std(x))

 mean 
 514.12 
 median 
 485.5 
 standard deviation 
 251.06430570672526


### 8. Normalize a 5x5 random matrix

In [90]:
from sklearn.preprocessing import normalize
x = np.random.randint(1,1000,25).reshape((5,5))
print('Normalize a 5x5 random matrix from 1 to 1000', '\n',normalize(x))

Normalize a 5x5 random matrix from 1 to 1000 
 [[0.42555673 0.26636934 0.27144304 0.5841099  0.57713356]
 [0.00898382 0.72469444 0.64683471 0.23732246 0.00449191]
 [0.58708851 0.30586743 0.50809382 0.38549407 0.39370952]
 [0.41824567 0.12246973 0.71171087 0.55072865 0.015405  ]
 [0.39401121 0.33984559 0.42808313 0.64037741 0.36867567]]


### 9. Consider an array of dimension (4,4,3), how to mulitply it by an array with dimensions (4,4)?

In [121]:
x = np.random.randint(1,10,(4,4,3))
y = np.random.randint(1,10,(4,4))
print(x,'\n',y)
x*y[:,:,None]


[[[2 1 1]
  [5 3 5]
  [5 5 2]
  [2 1 8]]

 [[9 4 9]
  [2 4 3]
  [9 9 8]
  [8 4 4]]

 [[4 7 1]
  [3 6 2]
  [6 8 7]
  [7 8 4]]

 [[8 5 6]
  [4 9 1]
  [2 3 2]
  [6 3 5]]] 
 [[3 2 1 7]
 [4 4 9 8]
 [4 9 6 8]
 [6 5 5 5]]


array([[[ 6,  3,  3],
        [10,  6, 10],
        [ 5,  5,  2],
        [14,  7, 56]],

       [[36, 16, 36],
        [ 8, 16, 12],
        [81, 81, 72],
        [64, 32, 32]],

       [[16, 28,  4],
        [27, 54, 18],
        [36, 48, 42],
        [56, 64, 32]],

       [[48, 30, 36],
        [20, 45,  5],
        [10, 15, 10],
        [30, 15, 25]]])